# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f143461e60bb9025c47e380825e6eb99371a29f371943646f208771c1e4319d34a031a1830f5e0ffcbaed073d3c4b83a6783ffd87159cfcb532b5a49c1579aef

test:
  secret_key_base: 5f5be5efdeeeb36f5646fc9d81acfad15dd5d180a90ef8f3f8785161307ca35c30584f0f13ba256e1d1f3b8c497da34ce17a2a6bdd49d2a5ab94af79c3fbe992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
